# SPDX-FileCopyrightText: 2026 Nikolay Govorov
# SPDX-License-Identifier: MPL-2.0

[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
publish = false
edition = "2024"
rust-version = "1.97"
version = "0.1.0"
license = "MPL-2.0"
authors = ["Nikolay Govorov <me@govorov.online>"]
homepage = "https://dimidiumlabs.io"
repository = "https://gilti.dev/platform"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = "warn"
