# SPDX-FileCopyrightText: 2026 Nikolay Govorov
# SPDX-License-Identifier: MPL-2.0

min_version = "2026.7.5"

[settings]
experimental = true

[tools]
"github:EmbarkStudios/cargo-about" = "0.8.4"
pipx = "1.16.7"
ruff = "0.16.3"
rust = { version = "1.97.1", profile = "minimal", components = ["clippy", "llvm-tools-preview", "rustfmt"] }

[task_config]
dir = "{{cwd}}"
includes = ["tasks"]
