// SPDX-FileCopyrightText: 2026 Nikolay Govorov
// SPDX-License-Identifier: MPL-2.0

use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write as _,
};

use lightningcss::{
    css_modules::{Config as CssModuleConfig, CssModuleReference, Pattern},
    rules::CssRule,
    stylesheet::{MinifyOptions, ParserOptions, PrinterOptions, StyleSheet},
};

use super::Error;

pub(super) fn compile_global(source: &str, logical_path: &str) -> Result<String, Error> {
    let mut sheet = StyleSheet::parse(
        source,
        ParserOptions {
            filename: logical_path.to_owned(),
            ..Default::default()
        },
    )
    .map_err(|error| Error::Css {
        path: logical_path.to_owned(),
        message: error.to_string(),
    })?;
    reject_imports(&sheet, logical_path)?;
    sheet
        .minify(MinifyOptions::default())
        .map_err(|error| Error::Css {
            path: logical_path.to_owned(),
            message: error.to_string(),
        })?;
    sheet
        .to_css(PrinterOptions {
            minify: true,
            ..Default::default()
        })
        .map(|result| result.code)
        .map_err(|error| Error::Css {
            path: logical_path.to_owned(),
            message: error.to_string(),
        })
}

pub(super) fn compile_module(
    source: &str,
    logical_path: &str,
) -> Result<(String, BTreeMap<String, String>), Error> {
    let config = CssModuleConfig {
        pattern: Pattern::parse("[hash]_[local]").expect("static pattern"),
        ..Default::default()
    };
    let mut sheet = StyleSheet::parse(
        source,
        ParserOptions {
            filename: logical_path.to_owned(),
            css_modules: Some(config),
            ..Default::default()
        },
    )
    .map_err(|error| Error::Css {
        path: logical_path.to_owned(),
        message: error.to_string(),
    })?;
    reject_imports(&sheet, logical_path)?;
    sheet
        .minify(MinifyOptions::default())
        .map_err(|error| Error::Css {
            path: logical_path.to_owned(),
            message: error.to_string(),
        })?;
    let result = sheet
        .to_css(PrinterOptions {
            minify: true,
            ..Default::default()
        })
        .map_err(|error| Error::Css {
            path: logical_path.to_owned(),
            message: error.to_string(),
        })?;
    let exports = result.exports.unwrap_or_default();
    if exports.values().any(|export| {
        export
            .composes
            .iter()
            .any(|reference| matches!(reference, CssModuleReference::Dependency { .. }))
    }) {
        return Err(Error::CrossFileComposes {
            path: logical_path.to_owned(),
        });
    }
    let exports = exports
        .into_iter()
        .map(|(local, export)| {
            let mut names = vec![export.name];
            names.extend(
                export
                    .composes
                    .into_iter()
                    .filter_map(|reference| match reference {
                        CssModuleReference::Local { name }
                        | CssModuleReference::Global { name } => Some(name),
                        CssModuleReference::Dependency { .. } => None,
                    }),
            );
            (local, names.join(" "))
        })
        .collect();
    Ok((result.code, exports))
}

fn reject_imports(sheet: &StyleSheet<'_>, path: &str) -> Result<(), Error> {
    if sheet
        .rules
        .0
        .iter()
        .any(|rule| matches!(rule, CssRule::Import(_)))
    {
        return Err(Error::Import {
            path: path.to_owned(),
        });
    }
    Ok(())
}

pub(super) fn render_bindings(modules: &BTreeMap<String, BTreeMap<String, String>>) -> String {
    let mut output = String::from("// @generated by dimidiumlabs-ui-build; do not edit.\n");
    for (module, exports) in modules {
        let _ = writeln!(output, "pub mod {module} {{");
        let mut used = BTreeSet::new();
        for (local, value) in exports {
            let constant = unique_identifier(screaming_identifier(local), &mut used);
            let _ = writeln!(output, "    pub const {constant}: &str = {value:?};");
        }
        output.push_str("}\n");
    }
    output
}

pub(super) fn rust_identifier(value: &str) -> String {
    safe_identifier(value, false)
}

fn screaming_identifier(value: &str) -> String {
    safe_identifier(value, true)
}

fn safe_identifier(value: &str, uppercase: bool) -> String {
    let mut identifier = String::new();
    for character in value.chars() {
        if character.is_ascii_alphanumeric() || character == '_' {
            identifier.push(if uppercase {
                character.to_ascii_uppercase()
            } else {
                character.to_ascii_lowercase()
            });
        } else {
            identifier.push('_');
        }
    }
    if identifier.is_empty() {
        identifier.push('_');
    }
    if identifier.as_bytes()[0].is_ascii_digit() {
        identifier.insert(0, '_');
    }
    if is_keyword(&identifier) {
        identifier.push('_');
    }
    identifier
}

fn unique_identifier(mut identifier: String, used: &mut BTreeSet<String>) -> String {
    let original = identifier.clone();
    let mut suffix = 2;
    while !used.insert(identifier.clone()) {
        identifier = format!("{original}_{suffix}");
        suffix += 1;
    }
    identifier
}

fn is_keyword(value: &str) -> bool {
    matches!(
        value,
        "as" | "async"
            | "await"
            | "break"
            | "const"
            | "continue"
            | "crate"
            | "dyn"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "gen"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "macro_rules"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "try"
            | "type"
            | "union"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "yield"
            | "abstract"
            | "become"
            | "box"
            | "do"
            | "final"
            | "macro"
            | "override"
            | "priv"
            | "typeof"
            | "unsized"
            | "virtual"
            | "with"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn identifiers_handle_keywords_invalid_characters_digits_and_collisions() {
        assert_eq!(rust_identifier("mod"), "mod_");
        assert_eq!(screaming_identifier("2-up!"), "_2_UP_");
        let rendered = render_bindings(&BTreeMap::from([(
            "mod_".to_owned(),
            BTreeMap::from([
                ("a-b".to_owned(), "one".to_owned()),
                ("a_b".to_owned(), "two".to_owned()),
            ]),
        )]));
        assert!(rendered.contains("pub mod mod_"));
        assert!(rendered.contains("pub const A_B"));
        assert!(rendered.contains("pub const A_B_2"));
    }

    #[test]
    fn modules_are_scoped_minified_and_rendered() {
        let (code, exports) = compile_module(
            ".card { color: red; } .child { composes: card; }",
            "src/card.module.css",
        )
        .unwrap();
        assert!(!code.contains(".card{"));
        assert!(exports["child"].contains("card"));
        assert!(
            render_bindings(&BTreeMap::from([("card".to_owned(), exports)]))
                .contains("pub const CHILD")
        );
    }

    #[test]
    fn rejects_cross_file_composes_and_imports() {
        assert!(matches!(
            compile_module(".a { composes: b from './b.module.css'; }", "x"),
            Err(Error::CrossFileComposes { .. })
        ));
        assert!(compile_module(".a { composes: b from global; }", "x").is_ok());
        assert!(compile_module(".a { --composes: b from './b.module.css'; }", "x").is_ok());
        assert!(matches!(
            compile_global("@import './other.css';", "x"),
            Err(Error::Import { .. })
        ));
    }
}
